import type { Episode } from "./dataset";

export type Level = "nominal" | "ordinal" | "scale";
/** Where a variable's values come from. Only "synthetic" is used in this version of the dataset. */
export type Source = "real" | "coded" | "synthetic";

export interface VariableMeta {
  name: keyof Episode;
  label: string;
  values: string;
  level: Level | "id";
  source: Source;
}

export const SOURCE_META: Record<Source, { label: string; text: string }> = {
  real: {
    label: "Real metadata",
    text: "Public facts about the episodes (titles, air dates, runtimes, ratings). None are used in this version: they could not be checked reliably when the lab was built, and invented ‘facts’ are worse than none.",
  },
  coded: {
    label: "Manually coded",
    text: "Counts a person would code by watching the episodes or reading licensed transcripts. None are used in this version.",
  },
  synthetic: {
    label: "Synthetic teaching variable",
    text: "Generated by a seeded script so that the exercises have realistic structure. Every variable in this dataset is synthetic.",
  },
};

export const VARIABLES: VariableMeta[] = [
  { name: "episode_id", label: "Generic episode label (not a real episode)", values: "S1E01 … S6E11", level: "id", source: "synthetic" },
  { name: "season", label: "Season", values: "1 – 6", level: "ordinal", source: "synthetic" },
  { name: "episode_number", label: "Episode number within season", values: "1 – 13", level: "ordinal", source: "synthetic" },
  { name: "runtime_minutes", label: "Runtime in minutes", values: "minutes", level: "scale", source: "synthetic" },
  { name: "episode_rating", label: "Average audience rating", values: "0 – 10, one decimal", level: "scale", source: "synthetic" },
  { name: "tony_present", label: "Tony appears in the episode", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "therapy_scene", label: "At least one therapy scene", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "family_dinner_scene", label: "At least one family dinner scene", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "violence_present", label: "Any violent event", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "major_violence", label: "At least one major (serious) violent event", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "death_present", label: "At least one death", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "death_count", label: "Number of deaths", values: "count", level: "scale", source: "synthetic" },
  { name: "violence_event_count", label: "Number of violent events", values: "count", level: "scale", source: "synthetic" },
  { name: "fuck_count", label: "Number of times the F-word is said", values: "count", level: "scale", source: "synthetic" },
  { name: "threat_count", label: "Number of explicit threats", values: "count", level: "scale", source: "synthetic" },
  { name: "food_scene_count", label: "Number of scenes involving food", values: "count", level: "scale", source: "synthetic" },
  { name: "therapy_scene_count", label: "Number of therapy scenes", values: "count", level: "scale", source: "synthetic" },
  { name: "family_conflict_count", label: "Family-related conflicts", values: "count", level: "scale", source: "synthetic" },
  { name: "crime_conflict_count", label: "Crime-related conflicts", values: "count", level: "scale", source: "synthetic" },
  { name: "number_major_characters", label: "Major characters on screen", values: "count", level: "scale", source: "synthetic" },
  { name: "number_locations", label: "Distinct locations", values: "count", level: "scale", source: "synthetic" },
  {
    name: "episode_tone",
    label: "Dominant tone",
    values: "1 = mostly family/personal, 2 = mixed, 3 = mostly organized crime/business",
    level: "ordinal",
    source: "synthetic",
  },
  { name: "finale_episode", label: "Season finale", values: "0 = no, 1 = yes", level: "nominal", source: "synthetic" },
  { name: "early_late", label: "Series period", values: "0 = seasons 1–3, 1 = seasons 4–6", level: "nominal", source: "synthetic" },
];

export const SYNTHETIC_NOTICE =
  "Synthetic teaching dataset inspired by The Sopranos. Values are created for statistical practice and are not factual episode statistics.";
